//! Cliche checks for proselint-wasm
//!
//! Detects overused phrases and expressions from multiple sources:
//! - Garner's Modern American Usage
//! - write-good
//! - GNU diction

use crate::check::{Check, Severity};

/// Get all cliche checks
pub fn get_checks() -> Vec<Check> {
    let mut checks = vec![
        // Wordy cliches with replacements
        Check::new(
            "cliches.at_this_point_in_time",
            "'At this point in time' is wordy. Use 'now' or 'currently'.",
            r"at this point in time",
        )
        .with_severity(Severity::Warning)
        .with_replacement("now"),

        Check::new(
            "cliches.due_to_the_fact",
            "'Due to the fact that' is wordy. Use 'because'.",
            r"due to the fact that",
        )
        .with_severity(Severity::Warning)
        .with_replacement("because"),

        Check::new(
            "cliches.in_order_to",
            "'In order to' is often wordy. 'To' is usually sufficient.",
            r"in order to",
        )
        .with_severity(Severity::Suggestion)
        .with_replacement("to"),

        Check::new(
            "cliches.point_in_time",
            "'Point in time' is usually redundant. Use 'time' or be more specific.",
            r"point in time",
        )
        .with_severity(Severity::Warning)
        .with_replacement("time"),
    ];

    // Garner's Modern American Usage cliches
    let garner_cliches = [
        "a fate worse than death",
        "alas and alack",
        "at the end of the day",
        "bald-faced lie",
        "between a rock and a hard place",
        "between Scylla and Charybdis",
        "between the devil and the deep blue sea",
        "betwixt and between",
        "blissful ignorance",
        "blow a fuse",
        "bulk large",
        "but that's another story",
        "cast aspersions",
        "chase a red herring",
        "comparing apples and oranges",
        "compleat",
        "conspicuous by its absence",
        "crystal clear",
        "cutting edge",
        "decision-making process",
        "dubious distinction",
        "duly authorized",
        "eyes peeled",
        "far be it from me",
        "fast and loose",
        "fills the bill",
        "first and foremost",
        "for free",
        "get with the program",
        "gilding the lily",
        "have a short fuse",
        "his own worst enemy",
        "hither and yon",
        "if you catch my drift",
        "in light of",
        "in the final analysis",
        "in the last analysis",
        "innocent bystander",
        "last but not least",
        "make a mockery of",
        "male chauvinism",
        "moment of truth",
        "more in sorrow than in anger",
        "more sinned against than sinning",
        "my better half",
        "nip in the bud",
        "olden days",
        "on the same page",
        "presidential timber",
        "pulled no punches",
        "quantum jump",
        "quantum leap",
        "sea change",
        "shirked his duties",
        "six of one, half a dozen of the other",
        "stretched to the breaking point",
        "the cream of the crop",
        "the cream rises to the top",
        "the straw that broke the camel's back",
        "thick as thieves",
        "thinking outside the box",
        "throw the baby out with the bathwater",
        "various and sundry",
        "viable alternative",
        "wax eloquent",
        "wax poetic",
        "wool pulled over our eyes",
        "writ large",
    ];

    for (i, phrase) in garner_cliches.iter().enumerate() {
        checks.push(Check::new(
            Box::leak(format!("cliches.garner.{}", i).into_boxed_str()),
            Box::leak(format!("'{}' is a cliche.", phrase).into_boxed_str()),
            phrase,
        ).with_severity(Severity::Suggestion));
    }

    // write-good cliches (extensive list)
    let write_good_cliches = [
        "a chip off the old block",
        "a clean slate",
        "a dark and stormy night",
        "a far cry",
        "a fine kettle of fish",
        "a loose cannon",
        "a penny saved is a penny earned",
        "a tough row to hoe",
        "a word to the wise",
        "ace in the hole",
        "acid test",
        "add insult to injury",
        "against all odds",
        "air your dirty laundry",
        "all fun and games",
        "all in a day's work",
        "all talk, no action",
        "all thumbs",
        "all your eggs in one basket",
        "almighty dollar",
        "an axe to grind",
        "another day, another dollar",
        "armed to the teeth",
        "as luck would have it",
        "as old as time",
        "as the crow flies",
        "at loose ends",
        "avoid like the plague",
        "babe in the woods",
        "back against the wall",
        "back in the saddle",
        "back to square one",
        "back to the drawing board",
        "bad to the bone",
        "badge of honor",
        "ballpark figure",
        "baptism by fire",
        "barking up the wrong tree",
        "bat out of hell",
        "be all and end all",
        "beat a dead horse",
        "beat around the bush",
        "been there, done that",
        "behind the eight ball",
        "bend over backwards",
        "benefit of the doubt",
        "bent out of shape",
        "best thing since sliced bread",
        "bet your bottom dollar",
        "better half",
        "better late than never",
        "better safe than sorry",
        "beyond the pale",
        "bide your time",
        "big as life",
        "big fish in a small pond",
        "bird in the hand",
        "birds of a feather flock together",
        "bite the bullet",
        "bite the dust",
        "black as coal",
        "blast from the past",
        "bleeding heart",
        "blessing in disguise",
        "blind ambition",
        "blind as a bat",
        "blind leading the blind",
        "blood is thicker than water",
        "blood sweat and tears",
        "blow off steam",
        "bolt from the blue",
        "bone to pick",
        "bored stiff",
        "bored to tears",
        "bottomless pit",
        "boys will be boys",
        "bright and early",
        "brings home the bacon",
        "broken record",
        "bull by the horns",
        "bull in a china shop",
        "burn the midnight oil",
        "burning question",
        "burning the candle at both ends",
        "burst your bubble",
        "bury the hatchet",
        "busy as a bee",
        "by hook or by crook",
        "call a spade a spade",
        "calm before the storm",
        "can of worms",
        "case of mistaken identity",
        "cat got your tongue",
        "caught red-handed",
        "checkered past",
        "chomping at the bit",
        "clear as a bell",
        "clear as mud",
        "cock and bull story",
        "cold shoulder",
        "come hell or high water",
        "cool as a cucumber",
        "cool, calm, and collected",
        "count your blessings",
        "crack of dawn",
        "crash course",
        "creature comforts",
        "cross that bridge when you come to it",
        "crushing blow",
        "cry like a baby",
        "cry me a river",
        "cry over spilt milk",
        "curiosity killed the cat",
        "cut and dried",
        "cut to the chase",
        "cute as a button",
        "dark before the dawn",
        "day in, day out",
        "dead as a doornail",
        "devil is in the details",
        "dime a dozen",
        "divide and conquer",
        "dog and pony show",
        "dog eat dog",
        "dog tired",
        "down and out",
        "down in the dumps",
        "down the hatch",
        "down to earth",
        "draw the line",
        "dressed to kill",
        "dressed to the nines",
        "dull as dishwater",
        "dyed in the wool",
        "eagle eye",
        "ear to the ground",
        "early bird catches the worm",
        "easier said than done",
        "easy as pie",
        "eat your heart out",
        "eat your words",
        "eleventh hour",
        "even the playing field",
        "every dog has its day",
        "everything but the kitchen sink",
        "eye for an eye",
        "face the music",
        "facts of life",
        "fair weather friend",
        "fall by the wayside",
        "fan the flames",
        "feast or famine",
        "feather your nest",
        "few and far between",
        "fifteen minutes of fame",
        "fish out of water",
        "fit as a fiddle",
        "fit to be tied",
        "flash in the pan",
        "flat as a pancake",
        "fly by night",
        "fly the coop",
        "follow your heart",
        "for all intents and purposes",
        "for the birds",
        "force of nature",
        "forgive and forget",
        "free and easy",
        "free as a bird",
        "fresh as a daisy",
        "full steam ahead",
        "fun in the sun",
        "gentle as a lamb",
        "get a kick out of",
        "get down and dirty",
        "get to the bottom of",
        "get your feet wet",
        "give and take",
        "go against the grain",
        "go for broke",
        "go the extra mile",
        "go with the flow",
        "goes without saying",
        "good as gold",
        "good things come to those who wait",
        "greased lightning",
        "green thumb",
        "green-eyed monster",
        "grist for the mill",
        "growing like a weed",
        "hair of the dog",
        "hand to mouth",
        "happy as a clam",
        "happy as a lark",
        "have a nice day",
        "have the last laugh",
        "head honcho",
        "head over heels",
        "hear a pin drop",
        "heard it through the grapevine",
        "heavy as lead",
        "hem and haw",
        "high and dry",
        "high and mighty",
        "high as a kite",
        "hit paydirt",
        "hold your horses",
        "hold your own",
        "honest as the day is long",
        "horns of a dilemma",
        "horse of a different color",
        "hot under the collar",
        "hour of need",
        "icing on the cake",
        "if the shoe fits",
        "in a jam",
        "in a jiffy",
        "in a nutshell",
        "in a pinch",
        "in hot water",
        "in the nick of time",
        "in the thick of it",
        "in your dreams",
        "ivory tower",
        "Jack of all trades",
        "jog your memory",
        "joined at the hip",
        "jump down your throat",
        "jump in with both feet",
        "jump on the bandwagon",
        "jump the gun",
        "jump to conclusions",
        "just the ticket",
        "justice is blind",
        "keep a stiff upper lip",
        "keep an eye on",
        "keep it simple, stupid",
        "keep up with the Joneses",
        "keep your chin up",
        "keep your fingers crossed",
        "kick the bucket",
        "kid in a candy store",
        "kill two birds with one stone",
        "kiss of death",
        "knock it out of the park",
        "knock on wood",
        "knock your socks off",
        "know the ropes",
        "labor of love",
        "ladder of success",
        "land on your feet",
        "lap of luxury",
        "last hurrah",
        "last-ditch effort",
        "law of the jungle",
        "lay down the law",
        "leaps and bounds",
        "let sleeping dogs lie",
        "let the cat out of the bag",
        "let the good times roll",
        "let your hair down",
        "lick your wounds",
        "life's a grind",
        "light at the end of the tunnel",
        "lighter than a feather",
        "like clockwork",
        "like father like son",
        "like taking candy from a baby",
        "lion's share",
        "live and learn",
        "live and let live",
        "long and short of it",
        "look before you leap",
        "loose cannon",
        "lose your head",
        "lose your temper",
        "low man on the totem pole",
        "luck of the draw",
        "make hay while the sun shines",
        "make my day",
        "make the best of it",
        "make your blood boil",
        "man of few words",
        "mark my words",
        "missed the boat on that one",
        "moment of glory",
        "money to burn",
        "more power to you",
        "more than one way to skin a cat",
        "movers and shakers",
        "moving experience",
        "naked as a jaybird",
        "naked truth",
        "neat as a pin",
        "needle in a haystack",
        "needless to say",
        "neither here nor there",
        "never look back",
        "never say never",
        "nip and tuck",
        "no guts, no glory",
        "no love lost",
        "no pain, no gain",
        "no skin off my back",
        "no stone unturned",
        "no time like the present",
        "no use crying over spilled milk",
        "nose to the grindstone",
        "not a minute's peace",
        "nothing to sneeze at",
        "nothing ventured nothing gained",
        "off the top of my head",
        "off the wall",
        "old hat",
        "older and wiser",
        "older than dirt",
        "on a roll",
        "on cloud nine",
        "on pins and needles",
        "on the bandwagon",
        "on the money",
        "on the nose",
        "on the spot",
        "on the tip of my tongue",
        "on thin ice",
        "once bitten, twice shy",
        "one brick short",
        "one foot in the grave",
        "one in a million",
        "only game in town",
        "open a can of worms",
        "open and shut case",
        "out of sight, out of mind",
        "out of the frying pan into the fire",
        "out of the woods",
        "out on a limb",
        "over a barrel",
        "pain and suffering",
        "par for the course",
        "part and parcel",
        "pass the buck",
        "patience is a virtue",
        "pay through the nose",
        "penny pincher",
        "perfect storm",
        "pig in a poke",
        "plain as day",
        "play by the rules",
        "play your cards right",
        "playing the field",
        "playing with fire",
        "pleased as punch",
        "plenty of fish in the sea",
        "poor as a church mouse",
        "pot calling the kettle black",
        "pretty as a picture",
        "pull a fast one",
        "pulling your leg",
        "pure as the driven snow",
        "put the cart before the horse",
        "put your best foot forward",
        "put your foot down",
        "quick as a bunny",
        "quick as lightning",
        "quiet as a dormouse",
        "rags to riches",
        "raining cats and dogs",
        "rank and file",
        "rat race",
        "reap what you sow",
        "red as a beet",
        "red herring",
        "reinvent the wheel",
        "rich and famous",
        "rings a bell",
        "ripe old age",
        "rise and shine",
        "road to hell is paved with good intentions",
        "rob Peter to pay Paul",
        "rub the wrong way",
        "ruled the roost",
        "running in circles",
        "sad but true",
        "sadder but wiser",
        "salt of the earth",
        "scared stiff",
        "scared to death",
        "second to none",
        "see eye to eye",
        "seen the light",
        "seize the day",
        "set the record straight",
        "set the world on fire",
        "sharp as a tack",
        "shoot for the moon",
        "shoot the breeze",
        "shot in the dark",
        "shoulder to the wheel",
        "sick as a dog",
        "sigh of relief",
        "signed, sealed, and delivered",
        "sink or swim",
        "skating on thin ice",
        "slept like a log",
        "slippery as an eel",
        "slow as molasses",
        "smart as a whip",
        "smooth as a baby's bottom",
        "sneaking suspicion",
        "snug as a bug in a rug",
        "sow wild oats",
        "speak of the devil",
        "spilled the beans",
        "spinning your wheels",
        "spitting image of",
        "spread like wildfire",
        "spring to life",
        "squeaky wheel gets the grease",
        "stands out like a sore thumb",
        "start from scratch",
        "stick in the mud",
        "still waters run deep",
        "stitch in time",
        "stop and smell the roses",
        "straight as an arrow",
        "strong as an ox",
        "stubborn as a mule",
        "stuff that dreams are made of",
        "sweating bullets",
        "take a load off",
        "take one for the team",
        "take the bait",
        "take the bull by the horns",
        "take the plunge",
        "takes one to know one",
        "takes two to tango",
        "the more the merrier",
        "the real deal",
        "the real McCoy",
        "the same old story",
        "thick as a brick",
        "thin as a rail",
        "this day and age",
        "this hurts me worse than it hurts you",
        "three sheets to the wind",
        "through thick and thin",
        "throw in the towel",
        "tighter than a drum",
        "time and time again",
        "time is of the essence",
        "tip of the iceberg",
        "tired but happy",
        "to coin a phrase",
        "to each his own",
        "to make a long story short",
        "to the best of my knowledge",
        "toe the line",
        "tongue in cheek",
        "too good to be true",
        "too hot to handle",
        "too numerous to mention",
        "tough as nails",
        "trial and error",
        "trials and tribulations",
        "tried and true",
        "trip down memory lane",
        "twist of fate",
        "two cents worth",
        "two peas in a pod",
        "ugly as sin",
        "under the gun",
        "under the same roof",
        "under the weather",
        "until the cows come home",
        "unvarnished truth",
        "up the creek",
        "uphill battle",
        "upper crust",
        "upset the applecart",
        "vain attempt",
        "vested interest",
        "waiting for the other shoe to drop",
        "wakeup call",
        "warm welcome",
        "watch your tongue",
        "water under the bridge",
        "weather the storm",
        "wet behind the ears",
        "what goes around comes around",
        "what you see is what you get",
        "when it rains, it pours",
        "when push comes to shove",
        "when the going gets tough, the tough get going",
        "white as a sheet",
        "whole ball of wax",
        "whole nine yards",
        "wild goose chase",
        "wisdom of the ages",
        "wise as an owl",
        "wolf at the door",
        "words fail me",
        "work like a dog",
        "world weary",
        "worst nightmare",
        "worth its weight in gold",
        "wrong side of the bed",
        "you are what you eat",
        "you can run but you can't hide",
        "you only live once",
        "young and foolish",
    ];

    for (i, phrase) in write_good_cliches.iter().enumerate() {
        checks.push(Check::new(
            Box::leak(format!("cliches.write_good.{}", i).into_boxed_str()),
            Box::leak(format!("'{}' is a cliche.", phrase).into_boxed_str()),
            phrase,
        ).with_severity(Severity::Suggestion));
    }

    // GNU diction cliches
    let diction_cliches = [
        "a matter of concern",
        "all things being equal",
        "as a last resort",
        "attached hereto",
        "by no means",
        "enclosed herewith",
        "if and when",
        "in reference to",
        "in short supply",
        "in the foreseeable future",
        "in the long run",
        "in the matter of",
        "it stands to reason",
        "many and diverse",
        "on the right track",
        "please feel free to",
        "pursuant to your request",
        "regarding the matter of",
        "slowly but surely",
        "this will acknowledge",
        "we wish to state",
    ];

    for (i, phrase) in diction_cliches.iter().enumerate() {
        checks.push(Check::new(
            Box::leak(format!("cliches.diction.{}", i).into_boxed_str()),
            Box::leak(format!("'{}' is a cliche.", phrase).into_boxed_str()),
            phrase,
        ).with_severity(Severity::Suggestion));
    }

    // Corporate/business cliches
    let corporate_cliches = [
        "think outside the box",
        "low-hanging fruit",
        "move the needle",
        "paradigm shift",
        "synergy",
        "take it to the next level",
        "game changer",
        "best practices",
        "going forward",
        "deep dive",
        "circle back",
        "touch base",
        "bandwidth",
        "core competency",
        "action item",
        "drill down",
        "deliverables",
        "stakeholder",
        "value add",
        "win-win",
        "scalable",
        "pivot",
        "disrupt",
        "ecosystem",
        "vertical",
        "horizontal",
        "synergize",
        "leverage",
        "optimize",
        "streamline",
    ];

    for (i, phrase) in corporate_cliches.iter().enumerate() {
        checks.push(Check::new(
            Box::leak(format!("cliches.corporate.{}", i).into_boxed_str()),
            Box::leak(format!("'{}' is corporate jargon/cliche.", phrase).into_boxed_str()),
            phrase,
        ).with_severity(Severity::Suggestion));
    }

    checks
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_at_the_end_of_the_day() {
        let checks = get_checks();
        let check = checks.iter().find(|c| c.id == "cliches.garner.2").unwrap();
        let results = check.run("At the end of the day, it doesn't matter.");
        assert_eq!(results.len(), 1);
    }

    #[test]
    fn test_in_order_to() {
        let checks = get_checks();
        let check = checks.iter().find(|c| c.id == "cliches.in_order_to").unwrap();
        let results = check.run("We need to do this in order to succeed.");
        assert_eq!(results.len(), 1);
    }
}
