//! Redundancy checks for proselint-wasm
//!
//! Detects redundant phrases and wordy expressions from:
//! - After the Deadline
//! - Garner's Modern American Usage

use crate::check::{Check, Severity};

/// Get all redundancy checks
pub fn get_checks() -> Vec<Check> {
    let mut checks = Vec::new();

    // After the Deadline redundancies with replacements
    let atd_redundancies: &[(&str, &str)] = &[
        ("added bonus", "bonus"),
        ("advance forward", "advance"),
        ("advance planning", "planning"),
        ("advance preview", "preview"),
        ("advance reservations", "reservations"),
        ("advance warning", "warning"),
        ("alternative choice", "alternative"),
        ("annual anniversary", "anniversary"),
        ("armed gunman", "gunman"),
        ("armed gunmen", "gunmen"),
        ("artificial prosthesis", "prosthesis"),
        ("ascend up", "ascend"),
        ("ask the question", "ask"),
        ("assemble together", "assemble"),
        ("attach together", "attach"),
        ("ATM machine", "ATM"),
        ("autobiography of my life", "autobiography"),
        ("bald-headed", "bald"),
        ("basic fundamentals", "fundamentals"),
        ("blend together", "blend"),
        ("brief cameo", "cameo"),
        ("brief moment", "moment"),
        ("burning hot", "hot"),
        ("cameo appearance", "cameo"),
        ("cancel out", "cancel"),
        ("cash money", "cash"),
        ("circle around", "circle"),
        ("circulate around", "circulate"),
        ("classify into groups", "classify"),
        ("climb up", "climb"),
        ("close proximity", "proximity"),
        ("closed fist", "fist"),
        ("collaborate together", "collaborate"),
        ("combine together", "combine"),
        ("commute back and forth", "commute"),
        ("compete with each other", "compete"),
        ("completely annihilate", "annihilate"),
        ("completely destroyed", "destroyed"),
        ("completely eliminate", "eliminate"),
        ("completely engulfed", "engulfed"),
        ("completely filled", "filled"),
        ("completely full", "full"),
        ("completely surround", "surround"),
        ("confer together", "confer"),
        ("connect together", "connect"),
        ("connect up", "connect"),
        ("consensus of opinion", "consensus"),
        ("cool down", "cool"),
        ("cooperate together", "cooperate"),
        ("crisis situation", "crisis"),
        ("crouch down", "crouch"),
        ("current trend", "trend"),
        ("descend down", "descend"),
        ("desirable benefits", "benefits"),
        ("different varieties", "varieties"),
        ("difficult dilemma", "dilemma"),
        ("disappear from sight", "disappear"),
        ("dive down", "dive"),
        ("drop down", "drop"),
        ("dwindle down", "dwindle"),
        ("each and every", "every"),
        ("earlier in time", "earlier"),
        ("eliminate altogether", "eliminate"),
        ("emergency situation", "emergency"),
        ("empty hole", "hole"),
        ("empty out", "empty"),
        ("enclosed herein", "enclosed"),
        ("end result", "result"),
        ("enter in", "enter"),
        ("enter into", "enter"),
        ("entirely eliminate", "eliminate"),
        ("equal to one another", "equal"),
        ("eradicate completely", "eradicate"),
        ("estimated at about", "estimated at"),
        ("exact replica", "replica"),
        ("exact same", "same"),
        ("fall down", "fall"),
        ("false pretense", "pretense"),
        ("few in number", "few"),
        ("filled to capacity", "filled"),
        ("final conclusion", "conclusion"),
        ("final end", "end"),
        ("final outcome", "outcome"),
        ("final ultimatum", "ultimatum"),
        ("first and foremost", "first"),
        ("first conceived", "conceived"),
        ("first of all", "first"),
        ("first time ever", "first time"),
        ("fly through the air", "fly"),
        ("focus in", "focus"),
        ("follow after", "follow"),
        ("foreign imports", "imports"),
        ("forever and ever", "forever"),
        ("forward planning", "planning"),
        ("free gift", "gift"),
        ("frozen ice", "ice"),
        ("frozen tundra", "tundra"),
        ("full to capacity", "full"),
        ("full satisfaction", "satisfaction"),
        ("fuse together", "fuse"),
        ("future forecast", "forecast"),
        ("future plans", "plans"),
        ("gather together", "gather"),
        ("gather up", "gather"),
        ("general consensus", "consensus"),
        ("general public", "public"),
        ("glowing ember", "ember"),
        ("grow in size", "grow"),
        ("hand in hand together", "hand in hand"),
        ("heat up", "heat"),
        ("HIV virus", "HIV"),
        ("hoist up", "hoist"),
        ("hollow tube", "tube"),
        ("honest truth", "truth"),
        ("hot water heater", "water heater"),
        ("hurry up", "hurry"),
        ("illustrated drawing", "drawing"),
        ("in actual fact", "in fact"),
        ("inner core", "core"),
        ("inner feelings", "feelings"),
        ("integrate together", "integrate"),
        ("interdependent on each other", "interdependent"),
        ("introduced for the first time", "introduced"),
        ("invisible to the eye", "invisible"),
        ("ISBN number", "ISBN"),
        ("joint collaboration", "collaboration"),
        ("kneel down", "kneel"),
        ("knowledgeable experts", "experts"),
        ("lift up", "lift"),
        ("live audience", "audience"),
        ("live witness", "witness"),
        ("local resident", "resident"),
        ("look ahead to the future", "look ahead"),
        ("major breakthrough", "breakthrough"),
        ("manually by hand", "manually"),
        ("may possibly", "may"),
        ("meet together", "meet"),
        ("meet with each other", "meet"),
        ("mental telepathy", "telepathy"),
        ("merge together", "merge"),
        ("might possibly", "might"),
        ("mix together", "mix"),
        ("mutual cooperation", "cooperation"),
        ("mutual respect for each other", "mutual respect"),
        ("native habitat", "habitat"),
        ("natural instinct", "instinct"),
        ("never at any time", "never"),
        ("new beginning", "beginning"),
        ("new innovation", "innovation"),
        ("new invention", "invention"),
        ("new recruit", "recruit"),
        ("none at all", "none"),
        ("now currently", "currently"),
        ("null and void", "void"),
        ("old adage", "adage"),
        ("old cliche", "cliche"),
        ("old custom", "custom"),
        ("old pioneer", "pioneer"),
        ("old proverb", "proverb"),
        ("open trench", "trench"),
        ("orbits around", "orbits"),
        ("originally created", "created"),
        ("originally discovered", "discovered"),
        ("outside in the yard", "in the yard"),
        ("over and done with", "done"),
        ("overexaggerate", "exaggerate"),
        ("overused cliche", "cliche"),
        ("passing fad", "fad"),
        ("past experience", "experience"),
        ("past history", "history"),
        ("past memories", "memories"),
        ("past records", "records"),
        ("penetrate through", "penetrate"),
        ("period of time", "period"),
        ("persistent obsession", "obsession"),
        ("personal belongings", "belongings"),
        ("personal charm", "charm"),
        ("personal friend", "friend"),
        ("personal friendship", "friendship"),
        ("personal opinion", "opinion"),
        ("PIN number", "PIN"),
        ("plan ahead", "plan"),
        ("plan in advance", "plan"),
        ("polar opposites", "opposites"),
        ("positive identification", "identification"),
        ("postpone until later", "postpone"),
        ("pouring down rain", "pouring rain"),
        ("present incumbent", "incumbent"),
        ("previously listed above", "listed above"),
        ("private industry", "industry"),
        ("probed into", "probed"),
        ("proceed ahead", "proceed"),
        ("proposed plan", "plan"),
        ("protest against", "protest"),
        ("raise up", "raise"),
        ("random chance", "chance"),
        ("reason is because", "reason is"),
        ("reason why", "reason"),
        ("recur again", "recur"),
        ("red in color", "red"),
        ("refer back", "refer"),
        ("reflect back", "reflect"),
        ("regular routine", "routine"),
        ("repeat again", "repeat"),
        ("reply back", "reply"),
        ("retreat back", "retreat"),
        ("return back", "return"),
        ("revert back", "revert"),
        ("rise up", "rise"),
        ("round circle", "circle"),
        ("round in shape", "round"),
        ("safe haven", "haven"),
        ("safe sanctuary", "sanctuary"),
        ("same exact", "same"),
        ("same identical", "identical"),
        ("scrutinize in detail", "scrutinize"),
        ("seek to find", "seek"),
        ("serious danger", "danger"),
        ("share together", "share"),
        ("shiny in appearance", "shiny"),
        ("short in duration", "short"),
        ("short in length", "short"),
        ("shrug shoulders", "shrug"),
        ("sink down", "sink"),
        ("skipped over", "skipped"),
        ("small in size", "small"),
        ("soft in texture", "soft"),
        ("soft to the touch", "soft"),
        ("specific details", "details"),
        ("spell out in detail", "spell out"),
        ("still lingers", "lingers"),
        ("still persists", "persists"),
        ("still remains", "remains"),
        ("sudden impulse", "impulse"),
        ("sufficient enough", "sufficient"),
        ("sum total", "total"),
        ("surrounded on all sides", "surrounded"),
        ("tall in height", "tall"),
        ("tall in stature", "tall"),
        ("temporary reprieve", "reprieve"),
        ("the month of May", "May"),
        ("the reason is because", "because"),
        ("time clock", "clock"),
        ("tiny bit", "bit"),
        ("total destruction", "destruction"),
        ("true facts", "facts"),
        ("truly sincere", "sincere"),
        ("twelve midnight", "midnight"),
        ("twelve noon", "noon"),
        ("two equal halves", "halves"),
        ("ultimate goal", "goal"),
        ("underground subway", "subway"),
        ("unexpected surprise", "surprise"),
        ("unfilled vacancy", "vacancy"),
        ("universal panacea", "panacea"),
        ("unnamed anonymous", "anonymous"),
        ("unsolved mystery", "mystery"),
        ("usual custom", "custom"),
        ("vacillate back and forth", "vacillate"),
        ("visible to the eye", "visible"),
        ("wall mural", "mural"),
        ("warn in advance", "warn"),
        ("whether or not", "whether"),
        ("whole entire", "whole"),
        ("write down", "write"),
    ];

    for (i, (pattern, replacement)) in atd_redundancies.iter().enumerate() {
        checks.push(
            Check::new(
                Box::leak(format!("redundancy.atd.{}", i).into_boxed_str()),
                Box::leak(format!("Redundancy. Try '{}'.", replacement).into_boxed_str()),
                pattern,
            )
            .with_severity(Severity::Warning)
            .with_replacement(replacement),
        );
    }

    // Garner's redundancies
    let garner_redundancies: &[(&str, &str)] = &[
        ("adequate enough", "adequate"),
        ("self-admitted", "admitted"),
        ("sworn affidavit", "affidavit"),
        ("mutual agreement", "agreement"),
        ("former alumnus", "alumnus"),
        ("directly antithetical", "antithetical"),
        ("approximately about", "approximately"),
        ("temporary bivouac", "bivouac"),
        ("bivouac camp", "bivouac"),
        ("but nevertheless", "but"),
        ("surrounding circumstances", "circumstances"),
        ("fellow collaborator", "collaborator"),
        ("fellow colleagues", "colleagues"),
        ("collocated together", "collocated"),
        ("self-complacent", "complacent"),
        ("self-confessed", "confessed"),
        ("consolidate together", "consolidate"),
        ("still continues to", "continues to"),
        ("mutually contradictory", "contradictory"),
        ("couple together", "couple"),
        ("serious crisis", "crisis"),
        ("most especially", "especially"),
        ("actual fact", "fact"),
        ("founding forefathers", "founding fathers"),
        ("free and gratis", "free"),
        ("free gratis", "free"),
        ("interact with each other", "interact"),
        ("large-size", "large"),
        ("meld together", "meld"),
        ("mingle together", "mingle"),
        ("mutual feelings for each other", "mutual feelings"),
        ("native-born citizen", "native citizen"),
        ("absolute necessity", "necessity"),
        ("blatantly obvious", "obvious"),
        ("pause for a moment", "pause"),
        ("pooled together", "pooled"),
        ("potable drinking water", "potable water"),
        ("reelected for another term", "reelected"),
        ("regress back", "regress"),
        ("repay back", "repay"),
        ("repeat back", "repeat"),
        ("repeat the same", "repeat"),
        ("repeated the same", "repeated"),
        ("brief respite", "respite"),
        ("closely scrutinize", "scrutinize"),
        ("software program", "software"),
        ("the whole entire nation", "the nation"),
        ("throughout the entire", "throughout the"),
        ("timpani drum", "timpani"),
        ("pair of twins", "twins"),
        ("various different", "various"),
        ("former veteran", "veteran"),
        ("professional vocation", "vocation"),
        ("while at the same time", "while"),
    ];

    for (i, (pattern, replacement)) in garner_redundancies.iter().enumerate() {
        checks.push(
            Check::new(
                Box::leak(format!("redundancy.garner.{}", i).into_boxed_str()),
                Box::leak(format!("Redundancy. Try '{}'.", replacement).into_boxed_str()),
                pattern,
            )
            .with_severity(Severity::Warning)
            .with_replacement(replacement),
        );
    }

    // RAS Syndrome (Redundant Acronym Syndrome)
    let ras_patterns: &[(&str, &str)] = &[
        ("ATM machine", "ATM"),
        ("PIN number", "PIN"),
        ("VIN number", "VIN"),
        ("HIV virus", "HIV"),
        ("LCD display", "LCD"),
        ("ISBN number", "ISBN"),
        ("UPC code", "UPC"),
        ("AC current", "AC"),
        ("DC current", "DC"),
        ("PDF format", "PDF"),
        ("HTML language", "HTML"),
        ("RAM memory", "RAM"),
        ("GPS system", "GPS"),
        ("SAT test", "SAT"),
        ("GRE exam", "GRE"),
    ];

    for (i, (pattern, replacement)) in ras_patterns.iter().enumerate() {
        checks.push(
            Check::new(
                Box::leak(format!("redundancy.ras.{}", i).into_boxed_str()),
                Box::leak(format!("RAS syndrome. Try '{}'.", replacement).into_boxed_str()),
                pattern,
            )
            .with_severity(Severity::Warning)
            .with_replacement(replacement),
        );
    }

    checks
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_close_proximity() {
        let checks = get_checks();
        let check = checks.iter().find(|c| c.id == "redundancy.atd.30").unwrap();
        let results = check.run("They were in close proximity to each other.");
        assert_eq!(results.len(), 1);
    }

    #[test]
    fn test_free_gift() {
        let checks = get_checks();
        let check = checks.iter().find(|c| c.id == "redundancy.atd.94").unwrap();
        let results = check.run("Get a free gift with your purchase!");
        assert_eq!(results.len(), 1);
    }
}
